# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kev/Documents/dev/tletc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kev/Documents/dev/tletc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kev/Documents/dev/tletc/CMakeFiles /home/kev/Documents/dev/tletc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kev/Documents/dev/tletc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tletc-linux32-d

# Build rule for target.
tletc-linux32-d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tletc-linux32-d
.PHONY : tletc-linux32-d

# fast build rule for target.
tletc-linux32-d/fast:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/build
.PHONY : tletc-linux32-d/fast

src/TLETC.o: src/TLETC.cpp.o

.PHONY : src/TLETC.o

# target to build an object file
src/TLETC.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/TLETC.cpp.o
.PHONY : src/TLETC.cpp.o

src/TLETC.i: src/TLETC.cpp.i

.PHONY : src/TLETC.i

# target to preprocess a source file
src/TLETC.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/TLETC.cpp.i
.PHONY : src/TLETC.cpp.i

src/TLETC.s: src/TLETC.cpp.s

.PHONY : src/TLETC.s

# target to generate assembly for a file
src/TLETC.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/TLETC.cpp.s
.PHONY : src/TLETC.cpp.s

src/graphics/BetterGL2DRenderer.o: src/graphics/BetterGL2DRenderer.cpp.o

.PHONY : src/graphics/BetterGL2DRenderer.o

# target to build an object file
src/graphics/BetterGL2DRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/BetterGL2DRenderer.cpp.o
.PHONY : src/graphics/BetterGL2DRenderer.cpp.o

src/graphics/BetterGL2DRenderer.i: src/graphics/BetterGL2DRenderer.cpp.i

.PHONY : src/graphics/BetterGL2DRenderer.i

# target to preprocess a source file
src/graphics/BetterGL2DRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/BetterGL2DRenderer.cpp.i
.PHONY : src/graphics/BetterGL2DRenderer.cpp.i

src/graphics/BetterGL2DRenderer.s: src/graphics/BetterGL2DRenderer.cpp.s

.PHONY : src/graphics/BetterGL2DRenderer.s

# target to generate assembly for a file
src/graphics/BetterGL2DRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/BetterGL2DRenderer.cpp.s
.PHONY : src/graphics/BetterGL2DRenderer.cpp.s

src/graphics/ShaderManager.o: src/graphics/ShaderManager.cpp.o

.PHONY : src/graphics/ShaderManager.o

# target to build an object file
src/graphics/ShaderManager.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/ShaderManager.cpp.o
.PHONY : src/graphics/ShaderManager.cpp.o

src/graphics/ShaderManager.i: src/graphics/ShaderManager.cpp.i

.PHONY : src/graphics/ShaderManager.i

# target to preprocess a source file
src/graphics/ShaderManager.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/ShaderManager.cpp.i
.PHONY : src/graphics/ShaderManager.cpp.i

src/graphics/ShaderManager.s: src/graphics/ShaderManager.cpp.s

.PHONY : src/graphics/ShaderManager.s

# target to generate assembly for a file
src/graphics/ShaderManager.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/ShaderManager.cpp.s
.PHONY : src/graphics/ShaderManager.cpp.s

src/graphics/ShaderProgram.o: src/graphics/ShaderProgram.cpp.o

.PHONY : src/graphics/ShaderProgram.o

# target to build an object file
src/graphics/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/ShaderProgram.cpp.o
.PHONY : src/graphics/ShaderProgram.cpp.o

src/graphics/ShaderProgram.i: src/graphics/ShaderProgram.cpp.i

.PHONY : src/graphics/ShaderProgram.i

# target to preprocess a source file
src/graphics/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/ShaderProgram.cpp.i
.PHONY : src/graphics/ShaderProgram.cpp.i

src/graphics/ShaderProgram.s: src/graphics/ShaderProgram.cpp.s

.PHONY : src/graphics/ShaderProgram.s

# target to generate assembly for a file
src/graphics/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/ShaderProgram.cpp.s
.PHONY : src/graphics/ShaderProgram.cpp.s

src/graphics/TextureManager.o: src/graphics/TextureManager.cpp.o

.PHONY : src/graphics/TextureManager.o

# target to build an object file
src/graphics/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/TextureManager.cpp.o
.PHONY : src/graphics/TextureManager.cpp.o

src/graphics/TextureManager.i: src/graphics/TextureManager.cpp.i

.PHONY : src/graphics/TextureManager.i

# target to preprocess a source file
src/graphics/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/TextureManager.cpp.i
.PHONY : src/graphics/TextureManager.cpp.i

src/graphics/TextureManager.s: src/graphics/TextureManager.cpp.s

.PHONY : src/graphics/TextureManager.s

# target to generate assembly for a file
src/graphics/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/TextureManager.cpp.s
.PHONY : src/graphics/TextureManager.cpp.s

src/graphics/TextureProgram.o: src/graphics/TextureProgram.cpp.o

.PHONY : src/graphics/TextureProgram.o

# target to build an object file
src/graphics/TextureProgram.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/TextureProgram.cpp.o
.PHONY : src/graphics/TextureProgram.cpp.o

src/graphics/TextureProgram.i: src/graphics/TextureProgram.cpp.i

.PHONY : src/graphics/TextureProgram.i

# target to preprocess a source file
src/graphics/TextureProgram.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/TextureProgram.cpp.i
.PHONY : src/graphics/TextureProgram.cpp.i

src/graphics/TextureProgram.s: src/graphics/TextureProgram.cpp.s

.PHONY : src/graphics/TextureProgram.s

# target to generate assembly for a file
src/graphics/TextureProgram.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/TextureProgram.cpp.s
.PHONY : src/graphics/TextureProgram.cpp.s

src/graphics/buffers/Buffer.o: src/graphics/buffers/Buffer.cpp.o

.PHONY : src/graphics/buffers/Buffer.o

# target to build an object file
src/graphics/buffers/Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/Buffer.cpp.o
.PHONY : src/graphics/buffers/Buffer.cpp.o

src/graphics/buffers/Buffer.i: src/graphics/buffers/Buffer.cpp.i

.PHONY : src/graphics/buffers/Buffer.i

# target to preprocess a source file
src/graphics/buffers/Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/Buffer.cpp.i
.PHONY : src/graphics/buffers/Buffer.cpp.i

src/graphics/buffers/Buffer.s: src/graphics/buffers/Buffer.cpp.s

.PHONY : src/graphics/buffers/Buffer.s

# target to generate assembly for a file
src/graphics/buffers/Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/Buffer.cpp.s
.PHONY : src/graphics/buffers/Buffer.cpp.s

src/graphics/buffers/IndexBuffer.o: src/graphics/buffers/IndexBuffer.cpp.o

.PHONY : src/graphics/buffers/IndexBuffer.o

# target to build an object file
src/graphics/buffers/IndexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/IndexBuffer.cpp.o
.PHONY : src/graphics/buffers/IndexBuffer.cpp.o

src/graphics/buffers/IndexBuffer.i: src/graphics/buffers/IndexBuffer.cpp.i

.PHONY : src/graphics/buffers/IndexBuffer.i

# target to preprocess a source file
src/graphics/buffers/IndexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/IndexBuffer.cpp.i
.PHONY : src/graphics/buffers/IndexBuffer.cpp.i

src/graphics/buffers/IndexBuffer.s: src/graphics/buffers/IndexBuffer.cpp.s

.PHONY : src/graphics/buffers/IndexBuffer.s

# target to generate assembly for a file
src/graphics/buffers/IndexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/IndexBuffer.cpp.s
.PHONY : src/graphics/buffers/IndexBuffer.cpp.s

src/graphics/buffers/VertexArray.o: src/graphics/buffers/VertexArray.cpp.o

.PHONY : src/graphics/buffers/VertexArray.o

# target to build an object file
src/graphics/buffers/VertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/VertexArray.cpp.o
.PHONY : src/graphics/buffers/VertexArray.cpp.o

src/graphics/buffers/VertexArray.i: src/graphics/buffers/VertexArray.cpp.i

.PHONY : src/graphics/buffers/VertexArray.i

# target to preprocess a source file
src/graphics/buffers/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/VertexArray.cpp.i
.PHONY : src/graphics/buffers/VertexArray.cpp.i

src/graphics/buffers/VertexArray.s: src/graphics/buffers/VertexArray.cpp.s

.PHONY : src/graphics/buffers/VertexArray.s

# target to generate assembly for a file
src/graphics/buffers/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/buffers/VertexArray.cpp.s
.PHONY : src/graphics/buffers/VertexArray.cpp.s

src/graphics/layers/Group.o: src/graphics/layers/Group.cpp.o

.PHONY : src/graphics/layers/Group.o

# target to build an object file
src/graphics/layers/Group.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/Group.cpp.o
.PHONY : src/graphics/layers/Group.cpp.o

src/graphics/layers/Group.i: src/graphics/layers/Group.cpp.i

.PHONY : src/graphics/layers/Group.i

# target to preprocess a source file
src/graphics/layers/Group.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/Group.cpp.i
.PHONY : src/graphics/layers/Group.cpp.i

src/graphics/layers/Group.s: src/graphics/layers/Group.cpp.s

.PHONY : src/graphics/layers/Group.s

# target to generate assembly for a file
src/graphics/layers/Group.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/Group.cpp.s
.PHONY : src/graphics/layers/Group.cpp.s

src/graphics/layers/Layer.o: src/graphics/layers/Layer.cpp.o

.PHONY : src/graphics/layers/Layer.o

# target to build an object file
src/graphics/layers/Layer.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/Layer.cpp.o
.PHONY : src/graphics/layers/Layer.cpp.o

src/graphics/layers/Layer.i: src/graphics/layers/Layer.cpp.i

.PHONY : src/graphics/layers/Layer.i

# target to preprocess a source file
src/graphics/layers/Layer.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/Layer.cpp.i
.PHONY : src/graphics/layers/Layer.cpp.i

src/graphics/layers/Layer.s: src/graphics/layers/Layer.cpp.s

.PHONY : src/graphics/layers/Layer.s

# target to generate assembly for a file
src/graphics/layers/Layer.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/Layer.cpp.s
.PHONY : src/graphics/layers/Layer.cpp.s

src/graphics/layers/TileLayer.o: src/graphics/layers/TileLayer.cpp.o

.PHONY : src/graphics/layers/TileLayer.o

# target to build an object file
src/graphics/layers/TileLayer.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/TileLayer.cpp.o
.PHONY : src/graphics/layers/TileLayer.cpp.o

src/graphics/layers/TileLayer.i: src/graphics/layers/TileLayer.cpp.i

.PHONY : src/graphics/layers/TileLayer.i

# target to preprocess a source file
src/graphics/layers/TileLayer.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/TileLayer.cpp.i
.PHONY : src/graphics/layers/TileLayer.cpp.i

src/graphics/layers/TileLayer.s: src/graphics/layers/TileLayer.cpp.s

.PHONY : src/graphics/layers/TileLayer.s

# target to generate assembly for a file
src/graphics/layers/TileLayer.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/layers/TileLayer.cpp.s
.PHONY : src/graphics/layers/TileLayer.cpp.s

src/graphics/renderables/Sprite2D.o: src/graphics/renderables/Sprite2D.cpp.o

.PHONY : src/graphics/renderables/Sprite2D.o

# target to build an object file
src/graphics/renderables/Sprite2D.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/renderables/Sprite2D.cpp.o
.PHONY : src/graphics/renderables/Sprite2D.cpp.o

src/graphics/renderables/Sprite2D.i: src/graphics/renderables/Sprite2D.cpp.i

.PHONY : src/graphics/renderables/Sprite2D.i

# target to preprocess a source file
src/graphics/renderables/Sprite2D.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/renderables/Sprite2D.cpp.i
.PHONY : src/graphics/renderables/Sprite2D.cpp.i

src/graphics/renderables/Sprite2D.s: src/graphics/renderables/Sprite2D.cpp.s

.PHONY : src/graphics/renderables/Sprite2D.s

# target to generate assembly for a file
src/graphics/renderables/Sprite2D.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/renderables/Sprite2D.cpp.s
.PHONY : src/graphics/renderables/Sprite2D.cpp.s

src/graphics/renderables/StaticSprite2D.o: src/graphics/renderables/StaticSprite2D.cpp.o

.PHONY : src/graphics/renderables/StaticSprite2D.o

# target to build an object file
src/graphics/renderables/StaticSprite2D.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/renderables/StaticSprite2D.cpp.o
.PHONY : src/graphics/renderables/StaticSprite2D.cpp.o

src/graphics/renderables/StaticSprite2D.i: src/graphics/renderables/StaticSprite2D.cpp.i

.PHONY : src/graphics/renderables/StaticSprite2D.i

# target to preprocess a source file
src/graphics/renderables/StaticSprite2D.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/renderables/StaticSprite2D.cpp.i
.PHONY : src/graphics/renderables/StaticSprite2D.cpp.i

src/graphics/renderables/StaticSprite2D.s: src/graphics/renderables/StaticSprite2D.cpp.s

.PHONY : src/graphics/renderables/StaticSprite2D.s

# target to generate assembly for a file
src/graphics/renderables/StaticSprite2D.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/graphics/renderables/StaticSprite2D.cpp.s
.PHONY : src/graphics/renderables/StaticSprite2D.cpp.s

src/linuxmain.o: src/linuxmain.cpp.o

.PHONY : src/linuxmain.o

# target to build an object file
src/linuxmain.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/linuxmain.cpp.o
.PHONY : src/linuxmain.cpp.o

src/linuxmain.i: src/linuxmain.cpp.i

.PHONY : src/linuxmain.i

# target to preprocess a source file
src/linuxmain.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/linuxmain.cpp.i
.PHONY : src/linuxmain.cpp.i

src/linuxmain.s: src/linuxmain.cpp.s

.PHONY : src/linuxmain.s

# target to generate assembly for a file
src/linuxmain.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/linuxmain.cpp.s
.PHONY : src/linuxmain.cpp.s

src/math/mat2f.o: src/math/mat2f.cpp.o

.PHONY : src/math/mat2f.o

# target to build an object file
src/math/mat2f.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/mat2f.cpp.o
.PHONY : src/math/mat2f.cpp.o

src/math/mat2f.i: src/math/mat2f.cpp.i

.PHONY : src/math/mat2f.i

# target to preprocess a source file
src/math/mat2f.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/mat2f.cpp.i
.PHONY : src/math/mat2f.cpp.i

src/math/mat2f.s: src/math/mat2f.cpp.s

.PHONY : src/math/mat2f.s

# target to generate assembly for a file
src/math/mat2f.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/mat2f.cpp.s
.PHONY : src/math/mat2f.cpp.s

src/math/mat4f.o: src/math/mat4f.cpp.o

.PHONY : src/math/mat4f.o

# target to build an object file
src/math/mat4f.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/mat4f.cpp.o
.PHONY : src/math/mat4f.cpp.o

src/math/mat4f.i: src/math/mat4f.cpp.i

.PHONY : src/math/mat4f.i

# target to preprocess a source file
src/math/mat4f.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/mat4f.cpp.i
.PHONY : src/math/mat4f.cpp.i

src/math/mat4f.s: src/math/mat4f.cpp.s

.PHONY : src/math/mat4f.s

# target to generate assembly for a file
src/math/mat4f.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/mat4f.cpp.s
.PHONY : src/math/mat4f.cpp.s

src/math/vec2f.o: src/math/vec2f.cpp.o

.PHONY : src/math/vec2f.o

# target to build an object file
src/math/vec2f.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec2f.cpp.o
.PHONY : src/math/vec2f.cpp.o

src/math/vec2f.i: src/math/vec2f.cpp.i

.PHONY : src/math/vec2f.i

# target to preprocess a source file
src/math/vec2f.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec2f.cpp.i
.PHONY : src/math/vec2f.cpp.i

src/math/vec2f.s: src/math/vec2f.cpp.s

.PHONY : src/math/vec2f.s

# target to generate assembly for a file
src/math/vec2f.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec2f.cpp.s
.PHONY : src/math/vec2f.cpp.s

src/math/vec2u.o: src/math/vec2u.cpp.o

.PHONY : src/math/vec2u.o

# target to build an object file
src/math/vec2u.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec2u.cpp.o
.PHONY : src/math/vec2u.cpp.o

src/math/vec2u.i: src/math/vec2u.cpp.i

.PHONY : src/math/vec2u.i

# target to preprocess a source file
src/math/vec2u.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec2u.cpp.i
.PHONY : src/math/vec2u.cpp.i

src/math/vec2u.s: src/math/vec2u.cpp.s

.PHONY : src/math/vec2u.s

# target to generate assembly for a file
src/math/vec2u.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec2u.cpp.s
.PHONY : src/math/vec2u.cpp.s

src/math/vec3f.o: src/math/vec3f.cpp.o

.PHONY : src/math/vec3f.o

# target to build an object file
src/math/vec3f.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec3f.cpp.o
.PHONY : src/math/vec3f.cpp.o

src/math/vec3f.i: src/math/vec3f.cpp.i

.PHONY : src/math/vec3f.i

# target to preprocess a source file
src/math/vec3f.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec3f.cpp.i
.PHONY : src/math/vec3f.cpp.i

src/math/vec3f.s: src/math/vec3f.cpp.s

.PHONY : src/math/vec3f.s

# target to generate assembly for a file
src/math/vec3f.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec3f.cpp.s
.PHONY : src/math/vec3f.cpp.s

src/math/vec4f.o: src/math/vec4f.cpp.o

.PHONY : src/math/vec4f.o

# target to build an object file
src/math/vec4f.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec4f.cpp.o
.PHONY : src/math/vec4f.cpp.o

src/math/vec4f.i: src/math/vec4f.cpp.i

.PHONY : src/math/vec4f.i

# target to preprocess a source file
src/math/vec4f.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec4f.cpp.i
.PHONY : src/math/vec4f.cpp.i

src/math/vec4f.s: src/math/vec4f.cpp.s

.PHONY : src/math/vec4f.s

# target to generate assembly for a file
src/math/vec4f.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/math/vec4f.cpp.s
.PHONY : src/math/vec4f.cpp.s

src/utils/FileIO.o: src/utils/FileIO.cpp.o

.PHONY : src/utils/FileIO.o

# target to build an object file
src/utils/FileIO.cpp.o:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/utils/FileIO.cpp.o
.PHONY : src/utils/FileIO.cpp.o

src/utils/FileIO.i: src/utils/FileIO.cpp.i

.PHONY : src/utils/FileIO.i

# target to preprocess a source file
src/utils/FileIO.cpp.i:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/utils/FileIO.cpp.i
.PHONY : src/utils/FileIO.cpp.i

src/utils/FileIO.s: src/utils/FileIO.cpp.s

.PHONY : src/utils/FileIO.s

# target to generate assembly for a file
src/utils/FileIO.cpp.s:
	$(MAKE) -f CMakeFiles/tletc-linux32-d.dir/build.make CMakeFiles/tletc-linux32-d.dir/src/utils/FileIO.cpp.s
.PHONY : src/utils/FileIO.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tletc-linux32-d"
	@echo "... edit_cache"
	@echo "... src/TLETC.o"
	@echo "... src/TLETC.i"
	@echo "... src/TLETC.s"
	@echo "... src/graphics/BetterGL2DRenderer.o"
	@echo "... src/graphics/BetterGL2DRenderer.i"
	@echo "... src/graphics/BetterGL2DRenderer.s"
	@echo "... src/graphics/ShaderManager.o"
	@echo "... src/graphics/ShaderManager.i"
	@echo "... src/graphics/ShaderManager.s"
	@echo "... src/graphics/ShaderProgram.o"
	@echo "... src/graphics/ShaderProgram.i"
	@echo "... src/graphics/ShaderProgram.s"
	@echo "... src/graphics/TextureManager.o"
	@echo "... src/graphics/TextureManager.i"
	@echo "... src/graphics/TextureManager.s"
	@echo "... src/graphics/TextureProgram.o"
	@echo "... src/graphics/TextureProgram.i"
	@echo "... src/graphics/TextureProgram.s"
	@echo "... src/graphics/buffers/Buffer.o"
	@echo "... src/graphics/buffers/Buffer.i"
	@echo "... src/graphics/buffers/Buffer.s"
	@echo "... src/graphics/buffers/IndexBuffer.o"
	@echo "... src/graphics/buffers/IndexBuffer.i"
	@echo "... src/graphics/buffers/IndexBuffer.s"
	@echo "... src/graphics/buffers/VertexArray.o"
	@echo "... src/graphics/buffers/VertexArray.i"
	@echo "... src/graphics/buffers/VertexArray.s"
	@echo "... src/graphics/layers/Group.o"
	@echo "... src/graphics/layers/Group.i"
	@echo "... src/graphics/layers/Group.s"
	@echo "... src/graphics/layers/Layer.o"
	@echo "... src/graphics/layers/Layer.i"
	@echo "... src/graphics/layers/Layer.s"
	@echo "... src/graphics/layers/TileLayer.o"
	@echo "... src/graphics/layers/TileLayer.i"
	@echo "... src/graphics/layers/TileLayer.s"
	@echo "... src/graphics/renderables/Sprite2D.o"
	@echo "... src/graphics/renderables/Sprite2D.i"
	@echo "... src/graphics/renderables/Sprite2D.s"
	@echo "... src/graphics/renderables/StaticSprite2D.o"
	@echo "... src/graphics/renderables/StaticSprite2D.i"
	@echo "... src/graphics/renderables/StaticSprite2D.s"
	@echo "... src/linuxmain.o"
	@echo "... src/linuxmain.i"
	@echo "... src/linuxmain.s"
	@echo "... src/math/mat2f.o"
	@echo "... src/math/mat2f.i"
	@echo "... src/math/mat2f.s"
	@echo "... src/math/mat4f.o"
	@echo "... src/math/mat4f.i"
	@echo "... src/math/mat4f.s"
	@echo "... src/math/vec2f.o"
	@echo "... src/math/vec2f.i"
	@echo "... src/math/vec2f.s"
	@echo "... src/math/vec2u.o"
	@echo "... src/math/vec2u.i"
	@echo "... src/math/vec2u.s"
	@echo "... src/math/vec3f.o"
	@echo "... src/math/vec3f.i"
	@echo "... src/math/vec3f.s"
	@echo "... src/math/vec4f.o"
	@echo "... src/math/vec4f.i"
	@echo "... src/math/vec4f.s"
	@echo "... src/utils/FileIO.o"
	@echo "... src/utils/FileIO.i"
	@echo "... src/utils/FileIO.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

